export const frontConfig = [
  {
    title: "JavaScript",
    collapsable: false,
    children: [
      "/front/JavaScript/Type",
      "/front/JavaScript/This",
      "/front/JavaScript/Copy",
      "/front/JavaScript/Prototype",
      "/front/JavaScript/ES6",
      "/front/JavaScript/Async",
      "/front/JavaScript/Promise",
      "/front/JavaScript/EventLoop",
      "/front/JavaScript/JS进阶",
      "/front/JavaScript/浏览器知识点",
      "/front/JavaScript/JS常见的设计模式",
      "/front/JavaScript/常见的数据结构",
      "/front/JavaScript/JS原理探索",
    ],
  },
  {
    title: "React系列",
    // collapsable: true,
    children: [
      "/front/React/React使用总结",
      "/front/React/Redux源码探索",
      "/front/React/React源码深入浅出",
      // 'React/React常见面试题',
      // 'React/Redux-Saga探索',
      // 'React/Dva探索',
      // 'React/Umi探索',
      "/front/React/Mobx使用总结",
      "/front/React/React运用技巧",
    ],
  },
  {
    title: "Webpack 系列",
    collapsable: true,
    children: [
      "/front/Webpack/初识Webpack",
      "/front/Webpack/Webpack基础",
      "/front/Webpack/Webpack进阶",
      "/front/Webpack/Webpack实战",
    ],
  },
];
